/// Hand-authored ABIs matching contracts/src exactly (the subset the agent + web
/// need). Run `pnpm --filter @turing-arena/shared sync-abis` after `forge build`
/// to regenerate these from artifacts and guarantee 1:1 fidelity.

export const identityRegistryAbi = [
  { type: "function", name: "register", stateMutability: "nonpayable", inputs: [{ name: "agentURI", type: "string" }], outputs: [{ name: "agentId", type: "uint256" }] },
  { type: "function", name: "register", stateMutability: "nonpayable", inputs: [], outputs: [{ name: "agentId", type: "uint256" }] },
  {
    type: "function",
    name: "register",
    stateMutability: "nonpayable",
    inputs: [
      { name: "agentURI", type: "string" },
      {
        name: "metadata",
        type: "tuple[]",
        components: [
          { name: "metadataKey", type: "string" },
          { name: "metadataValue", type: "bytes" },
        ],
      },
    ],
    outputs: [{ name: "agentId", type: "uint256" }],
  },
  { type: "function", name: "ownerOf", stateMutability: "view", inputs: [{ name: "agentId", type: "uint256" }], outputs: [{ name: "", type: "address" }] },
  { type: "function", name: "isController", stateMutability: "view", inputs: [{ name: "agentId", type: "uint256" }, { name: "account", type: "address" }], outputs: [{ name: "", type: "bool" }] },
  { type: "function", name: "exists", stateMutability: "view", inputs: [{ name: "agentId", type: "uint256" }], outputs: [{ name: "", type: "bool" }] },
  { type: "function", name: "agentURI", stateMutability: "view", inputs: [{ name: "agentId", type: "uint256" }], outputs: [{ name: "", type: "string" }] },
  { type: "function", name: "tokenURI", stateMutability: "view", inputs: [{ name: "tokenId", type: "uint256" }], outputs: [{ name: "", type: "string" }] },
  { type: "function", name: "totalAgents", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "getAgentWallet", stateMutability: "view", inputs: [{ name: "agentId", type: "uint256" }], outputs: [{ name: "", type: "address" }] },
  { type: "function", name: "walletNonce", stateMutability: "view", inputs: [{ name: "agentId", type: "uint256" }], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "getMetadata", stateMutability: "view", inputs: [{ name: "agentId", type: "uint256" }, { name: "key", type: "string" }], outputs: [{ name: "", type: "bytes" }] },
  { type: "function", name: "setMetadata", stateMutability: "nonpayable", inputs: [{ name: "agentId", type: "uint256" }, { name: "key", type: "string" }, { name: "value", type: "bytes" }], outputs: [] },
  { type: "function", name: "setAgentURI", stateMutability: "nonpayable", inputs: [{ name: "agentId", type: "uint256" }, { name: "newURI", type: "string" }], outputs: [] },
  { type: "function", name: "setAgentWallet", stateMutability: "nonpayable", inputs: [{ name: "agentId", type: "uint256" }, { name: "newWallet", type: "address" }, { name: "deadline", type: "uint256" }, { name: "signature", type: "bytes" }], outputs: [] },
  {
    type: "event",
    name: "Registered",
    inputs: [
      { name: "agentId", type: "uint256", indexed: true },
      { name: "agentURI", type: "string", indexed: false },
      { name: "owner", type: "address", indexed: true },
    ],
  },
] as const;

export const reputationRegistryAbi = [
  {
    type: "function",
    name: "giveFeedback",
    stateMutability: "nonpayable",
    inputs: [
      { name: "agentId", type: "uint256" },
      { name: "value", type: "int128" },
      { name: "valueDecimals", type: "uint8" },
      { name: "tag1", type: "string" },
      { name: "tag2", type: "string" },
      { name: "endpoint", type: "string" },
      { name: "feedbackURI", type: "string" },
      { name: "feedbackHash", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "getSummary",
    stateMutability: "view",
    inputs: [
      { name: "agentId", type: "uint256" },
      { name: "clientAddresses", type: "address[]" },
      { name: "tag1", type: "string" },
      { name: "tag2", type: "string" },
    ],
    outputs: [
      { name: "count", type: "uint64" },
      { name: "summaryValue", type: "int128" },
      { name: "summaryValueDecimals", type: "uint8" },
    ],
  },
  {
    type: "function",
    name: "readFeedback",
    stateMutability: "view",
    inputs: [{ name: "agentId", type: "uint256" }, { name: "clientAddress", type: "address" }, { name: "feedbackIndex", type: "uint64" }],
    outputs: [
      { name: "value", type: "int128" },
      { name: "valueDecimals", type: "uint8" },
      { name: "tag1", type: "string" },
      { name: "tag2", type: "string" },
      { name: "isRevoked", type: "bool" },
    ],
  },
  { type: "function", name: "getClients", stateMutability: "view", inputs: [{ name: "agentId", type: "uint256" }], outputs: [{ name: "", type: "address[]" }] },
  { type: "function", name: "getLastIndex", stateMutability: "view", inputs: [{ name: "agentId", type: "uint256" }, { name: "clientAddress", type: "address" }], outputs: [{ name: "", type: "uint64" }] },
  { type: "function", name: "getIdentityRegistry", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  {
    type: "event",
    name: "NewFeedback",
    inputs: [
      { name: "agentId", type: "uint256", indexed: true },
      { name: "clientAddress", type: "address", indexed: true },
      { name: "feedbackIndex", type: "uint64", indexed: false },
      { name: "value", type: "int128", indexed: false },
      { name: "valueDecimals", type: "uint8", indexed: false },
      { name: "indexedTag1", type: "string", indexed: true },
      { name: "tag1", type: "string", indexed: false },
      { name: "tag2", type: "string", indexed: false },
      { name: "endpoint", type: "string", indexed: false },
      { name: "feedbackURI", type: "string", indexed: false },
      { name: "feedbackHash", type: "bytes32", indexed: false },
    ],
  },
] as const;

const ROUND_TUPLE = {
  name: "",
  type: "tuple",
  components: [
    { name: "asset", type: "bytes32" },
    { name: "oracle", type: "address" },
    { name: "commitDeadline", type: "uint64" },
    { name: "revealDeadline", type: "uint64" },
    { name: "settleTime", type: "uint64" },
    { name: "settled", type: "bool" },
    { name: "rewardClaimed", type: "bool" },
    { name: "hasWinner", type: "bool" },
    { name: "revealCount", type: "uint32" },
    { name: "settleCursor", type: "uint32" },
    { name: "entryPrice", type: "uint256" },
    { name: "settlePrice", type: "uint256" },
    { name: "stake", type: "uint256" },
    { name: "prizePool", type: "uint256" },
    { name: "topAgentId", type: "uint256" },
    { name: "topScore", type: "int256" },
    { name: "title", type: "string" },
  ],
} as const;

const ENTRY_TUPLE = {
  name: "",
  type: "tuple",
  components: [
    { name: "commitHash", type: "bytes32" },
    { name: "revealed", type: "bool" },
    { name: "scored", type: "bool" },
    { name: "confidence", type: "uint8" },
    { name: "predictedBps", type: "int256" },
    { name: "rationaleHash", type: "bytes32" },
    { name: "score", type: "int256" },
  ],
} as const;

export const proofOfAlphaAbi = [
  { type: "function", name: "VERSION", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "string" }] },
  { type: "function", name: "MAX_ABS_BPS", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "int256" }] },
  { type: "function", name: "roundCount", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { type: "function", name: "isOperator", stateMutability: "view", inputs: [{ name: "", type: "address" }], outputs: [{ name: "", type: "bool" }] },
  { type: "function", name: "totalScore", stateMutability: "view", inputs: [{ name: "agentId", type: "uint256" }], outputs: [{ name: "", type: "int256" }] },
  { type: "function", name: "roundsPlayed", stateMutability: "view", inputs: [{ name: "agentId", type: "uint256" }], outputs: [{ name: "", type: "uint32" }] },
  { type: "function", name: "correctCount", stateMutability: "view", inputs: [{ name: "agentId", type: "uint256" }], outputs: [{ name: "", type: "uint32" }] },
  {
    type: "function",
    name: "getAgentStats",
    stateMutability: "view",
    inputs: [{ name: "agentId", type: "uint256" }],
    outputs: [
      { name: "score", type: "int256" },
      { name: "played", type: "uint32" },
      { name: "correct", type: "uint32" },
      { name: "accuracyBps", type: "uint32" },
    ],
  },
  { type: "function", name: "realizedBps", stateMutability: "view", inputs: [{ name: "roundId", type: "uint256" }], outputs: [{ name: "", type: "int256" }] },
  { type: "function", name: "getRound", stateMutability: "view", inputs: [{ name: "roundId", type: "uint256" }], outputs: [ROUND_TUPLE] },
  { type: "function", name: "getEntry", stateMutability: "view", inputs: [{ name: "roundId", type: "uint256" }, { name: "agentId", type: "uint256" }], outputs: [ENTRY_TUPLE] },
  { type: "function", name: "getParticipants", stateMutability: "view", inputs: [{ name: "roundId", type: "uint256" }], outputs: [{ name: "", type: "uint256[]" }] },
  { type: "function", name: "participantCount", stateMutability: "view", inputs: [{ name: "roundId", type: "uint256" }], outputs: [{ name: "", type: "uint256" }] },
  {
    type: "function",
    name: "computeCommit",
    stateMutability: "pure",
    inputs: [
      { name: "agentId", type: "uint256" },
      { name: "predictedBps", type: "int256" },
      { name: "confidence", type: "uint8" },
      { name: "rationaleHash", type: "bytes32" },
      { name: "salt", type: "bytes32" },
    ],
    outputs: [{ name: "", type: "bytes32" }],
  },
  { type: "function", name: "assetId", stateMutability: "pure", inputs: [{ name: "symbol", type: "string" }], outputs: [{ name: "", type: "bytes32" }] },
  {
    type: "function",
    name: "openRound",
    stateMutability: "nonpayable",
    inputs: [
      { name: "asset", type: "bytes32" },
      { name: "oracle", type: "address" },
      { name: "title", type: "string" },
      { name: "commitDeadline", type: "uint64" },
      { name: "revealDeadline", type: "uint64" },
      { name: "settleTime", type: "uint64" },
      { name: "stake", type: "uint256" },
    ],
    outputs: [{ name: "roundId", type: "uint256" }],
  },
  { type: "function", name: "commit", stateMutability: "payable", inputs: [{ name: "roundId", type: "uint256" }, { name: "agentId", type: "uint256" }, { name: "commitHash", type: "bytes32" }], outputs: [] },
  {
    type: "function",
    name: "reveal",
    stateMutability: "nonpayable",
    inputs: [
      { name: "roundId", type: "uint256" },
      { name: "agentId", type: "uint256" },
      { name: "predictedBps", type: "int256" },
      { name: "confidence", type: "uint8" },
      { name: "rationaleHash", type: "bytes32" },
      { name: "salt", type: "bytes32" },
    ],
    outputs: [],
  },
  { type: "function", name: "settle", stateMutability: "nonpayable", inputs: [{ name: "roundId", type: "uint256" }, { name: "maxAgents", type: "uint256" }], outputs: [] },
  { type: "function", name: "claimReward", stateMutability: "nonpayable", inputs: [{ name: "roundId", type: "uint256" }, { name: "agentId", type: "uint256" }], outputs: [] },
  { type: "function", name: "setOperator", stateMutability: "nonpayable", inputs: [{ name: "operator", type: "address" }, { name: "allowed", type: "bool" }], outputs: [] },
  {
    type: "event",
    name: "RoundOpened",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true },
      { name: "asset", type: "bytes32", indexed: true },
      { name: "title", type: "string", indexed: false },
      { name: "oracle", type: "address", indexed: false },
      { name: "entryPrice", type: "uint256", indexed: false },
      { name: "commitDeadline", type: "uint64", indexed: false },
      { name: "revealDeadline", type: "uint64", indexed: false },
      { name: "settleTime", type: "uint64", indexed: false },
      { name: "stake", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Committed",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true },
      { name: "agentId", type: "uint256", indexed: true },
      { name: "by", type: "address", indexed: true },
      { name: "commitHash", type: "bytes32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Revealed",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true },
      { name: "agentId", type: "uint256", indexed: true },
      { name: "predictedBps", type: "int256", indexed: false },
      { name: "confidence", type: "uint8", indexed: false },
      { name: "rationaleHash", type: "bytes32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "EntryScored",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true },
      { name: "agentId", type: "uint256", indexed: true },
      { name: "predictedBps", type: "int256", indexed: false },
      { name: "confidence", type: "uint8", indexed: false },
      { name: "actualBps", type: "int256", indexed: false },
      { name: "score", type: "int256", indexed: false },
      { name: "correct", type: "bool", indexed: false },
    ],
  },
  {
    type: "event",
    name: "RoundSettled",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true },
      { name: "settlePrice", type: "uint256", indexed: false },
      { name: "actualBps", type: "int256", indexed: false },
      { name: "topAgentId", type: "uint256", indexed: false },
      { name: "topScore", type: "int256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "RewardClaimed",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true },
      { name: "agentId", type: "uint256", indexed: true },
      { name: "to", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
] as const;

export const reporterPriceOracleAbi = [
  { type: "function", name: "decimals", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint8" }] },
  { type: "function", name: "getPrice", stateMutability: "view", inputs: [{ name: "asset", type: "bytes32" }], outputs: [{ name: "price", type: "uint256" }, { name: "updatedAt", type: "uint256" }] },
  {
    type: "function",
    name: "getObservation",
    stateMutability: "view",
    inputs: [{ name: "asset", type: "bytes32" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "price", type: "uint256" },
          { name: "updatedAt", type: "uint256" },
          { name: "source", type: "string" },
        ],
      },
    ],
  },
  { type: "function", name: "reportPrice", stateMutability: "nonpayable", inputs: [{ name: "asset", type: "bytes32" }, { name: "price", type: "uint256" }, { name: "source", type: "string" }], outputs: [] },
  { type: "function", name: "isReporter", stateMutability: "view", inputs: [{ name: "", type: "address" }], outputs: [{ name: "", type: "bool" }] },
  { type: "function", name: "setReporter", stateMutability: "nonpayable", inputs: [{ name: "reporter", type: "address" }, { name: "allowed", type: "bool" }], outputs: [] },
  {
    type: "event",
    name: "PriceReported",
    inputs: [
      { name: "asset", type: "bytes32", indexed: true },
      { name: "price", type: "uint256", indexed: false },
      { name: "source", type: "string", indexed: false },
      { name: "reporter", type: "address", indexed: true },
    ],
  },
] as const;

export const championVaultAbi = [
  { type: "function", name: "holdings", stateMutability: "view", inputs: [], outputs: [{ name: "base", type: "uint256" }, { name: "quote", type: "uint256" }] },
  { type: "function", name: "traded", stateMutability: "view", inputs: [{ name: "roundId", type: "uint256" }], outputs: [{ name: "", type: "bool" }] },
  { type: "function", name: "baseToken", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  { type: "function", name: "quoteToken", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "address" }] },
  { type: "function", name: "isKeeper", stateMutability: "view", inputs: [{ name: "", type: "address" }], outputs: [{ name: "", type: "bool" }] },
  {
    type: "function",
    name: "executeChampionTrade",
    stateMutability: "nonpayable",
    inputs: [
      { name: "roundId", type: "uint256" },
      { name: "amountIn", type: "uint256" },
      { name: "amountOutMin", type: "uint256" },
      { name: "deadline", type: "uint256" },
    ],
    outputs: [{ name: "amountOut", type: "uint256" }],
  },
  {
    type: "event",
    name: "ChampionTradeExecuted",
    inputs: [
      { name: "roundId", type: "uint256", indexed: true },
      { name: "agentId", type: "uint256", indexed: true },
      { name: "long", type: "bool", indexed: false },
      { name: "tokenIn", type: "address", indexed: false },
      { name: "tokenOut", type: "address", indexed: false },
      { name: "amountIn", type: "uint256", indexed: false },
      { name: "amountOut", type: "uint256", indexed: false },
    ],
  },
] as const;
